### ISSUE TITLE
jwt_claim() discarding empty substructures

### ISSUE THREAD

**Issue by gvwilson** [jeroen/jose#13]
We want to encode this structure with `jwt_claim()` in order to embed a [Metabase](http://metabase.com) question in a Shiny application:

```
{
  "resource": {"question": 4},
  "params": {}, # empty but required
  "exp": 123456789 # current time + 10 minutes
```

Metabase requires the `params` key to be present at the top level even if the value is empty. However, line 28 of `R/claim.R` appears to throw away any empty substructures at the top level of the claim, and on the receiving end after decryption the `params` key is missing. Our workaround is:

```
params <- list()
names(params) <- character(0)
claim <- structure(list(exp = unbox(expiry), resource = list(question = unbox(1)), params = params),
                   class = c("jwt_claim", "list"))
token <- jwt_encode_hmac(claim, secret = METABASE_SECRET_KEY)
```

(We have to contruct `params` this way rather than simply using a list because `jsonlite` converts `list()` without names to `[]` rather than `{}`). Can `jwt_claim()` take an optional argument specifying that empty structures are to be retained?

**Comment by jeroen** [comment]
Maybe instead of filtering by length, we should just filter out NULL fields?

**Comment by jeroen** [comment]
Can you test if it now works for you?

**Comment by gvwilson** [comment]
Sure, but may I ask why you're filtering at all? Suppose I want to create a claim like this:

```
{
  "exp": 123456789,
  "resource": {"question": 4},
  "thresholds": []
}
```

If I construct the claim as `jwt_claim(exp = 123456789, resource = list(question = 4), thresholds = integer(0))`, I think my (empty) thresholds will be thrown away by your patch. Do empty structures affect the encoding somehow, or is this an optimization?

**Comment by jeroen** [comment]
I don't think it makes sense to include all unset parameters, which are NULL by default. So I want to filter those out. If you want to add a `{}` or `[]` you can use an empty list?

**Comment by gvwilson** [comment]
Ah - that makes sense. In that case, yes, filtering out anything that is null but keeping things of length 0 would handle every case I can think of - thank you.
